### ISSUE TITLE
Loading config file

### ISSUE THREAD

**Issue by baadc0de** [moleculerjs/moleculer-cli#10]
See: 

https://github.com/moleculerjs/moleculer-cli/blob/0d6f9a5093f79663665983b687bc6debc72d3fb5/src/connect/index.js#L88

This could probably be "fixed" in moleculer core, however.

**Comment by icebob** [comment]
According to gitter suggestion, I will add a `--config <filename>` param, which loads a `moleculer.config.js` file like Moleculer Runner

**Comment by icebob** [comment]
Implemented. Tomorrow I'll try to make a release

**Comment by icebob** [comment]
Released: https://github.com/moleculerjs/moleculer-cli/releases/tag/v0.5.7
