### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by molotsnk** [moleculerjs/moleculer-cli#18]
Hi, try to run moleculer cli. 

- [2018-11-29T07:55:24.645Z] INFO  cli-x0rium-tm1701-24724/BROKER: Moleculer v0.13.4 is starting...
- [2018-11-29T07:55:24.645Z] INFO  cli-x0rium-tm1701-24724/BROKER: Node ID: cli-x0rium-tm1701-24724
- [2018-11-29T07:55:24.645Z] INFO  cli-x0rium-tm1701-24724/BROKER: Namespace: <not defined>
- [2018-11-29T07:55:24.646Z] INFO  cli-x0rium-tm1701-24724/REGISTRY: Strategy: RoundRobinStrategy
- [2018-11-29T07:55:24.649Z] INFO  cli-x0rium-tm1701-24724/BROKER: Serializer: JSONSerializer
- [2018-11-29T07:55:24.650Z] INFO  cli-x0rium-tm1701-24724/BROKER: Registered 10 internal middleware(s).
- [2018-11-29T07:55:24.656Z] INFO  cli-x0rium-tm1701-24724/REGISTRY: '$node' service is registered.
- [2018-11-29T07:55:24.657Z] INFO  cli-x0rium-tm1701-24724/BROKER: ServiceBroker with 1 service(s) is started successfully.
**- The 'moleculer-repl' package is missing. Please install it with 'npm install moleculer-repl' command.**
- [2018-11-29T07:55:24.792Z] ERROR cli-x0rium-tm1701-24724/BROKER: The 'moleculer-repl' package is missing. Please install it with 'npm install moleculer-repl' command.
- [2018-11-29T07:55:24.793Z] INFO  cli-x0rium-tm1701-24724/BROKER: ServiceBroker is stopped. Good bye.

I try to install `npm install moleculer-repl` but nothing changes. Reinstall npm i moleculer-cli -g the same..  Any ideas? Thanks!

**Comment by icebob** [comment]
What command did you use to start it?

**Comment by molotsnk** [comment]
moleculer connect nats://nats:4222

**Comment by icebob** [comment]
Interesting. Once I could reproduce but now can't. Could you try to uninstall & install again?
`npm uninstall moleculer-cli -g && npm install moleculer-cli -g`

**Comment by molotsnk** [comment]
It's working for me. Great thanks!
