### ISSUE TITLE
Error on using moleculer init

### ISSUE THREAD

**Issue by pabhishek-deloitte** [moleculerjs/moleculer-cli#19]
I get the following error on trying to initialise a moleculer project - 
Failed to download repo from 'moleculerjs/moleculer-template-project'!

**Comment by icebob** [comment]
do you have installed git?

**Comment by pabhishek-deloitte** [comment]
Yep I do. I am able to clone but the template/package.json has some uncompiled attributes.

**Comment by icebob** [comment]
Could you explain?

**Comment by pabhishek-deloitte** [comment]
Yep, I am referring to the references like {{#jest}} [https://github.com/moleculerjs/moleculer-template-project/blob/master/template/package.json](here). I suppose these get populated based on the options we choose when we run `moleculer init`.

**Comment by icebob** [comment]
Yes, but it is populated after repo downloading.

**Comment by pabhishek-deloitte** [comment]
The download fails when using `moleculer init` with the error `Failed to download repo from 'moleculerjs/moleculer-template-project'!`. It is not a proxy issue. Here are other details - 

OS - macOS High Sierra v 10.13.6 (17G5019)
Moleculer v0.13.4
npm V5.6.0
