### ISSUE TITLE
Non-interactive init with answer files

### ISSUE THREAD

**Issue by morkeleb** [moleculerjs/moleculer-cli#24]
I'd like to be able to run the init function in a non-interactive way.
Supplying a file with the answers for the init function.

jHipster is using yeoman for their init scripts and it saves all their answers in a .yo.rc.json file that contains all the answers to the questions that were posed.

As a bonus they can use that file to for future upgrade scripts.

**Comment by icebob** [comment]
Done: `--answers <answer-json-filename>`
