### ISSUE TITLE
Outdated npm Page

### ISSUE THREAD

**Issue by AmberParsons** [moleculerjs/moleculer-cli#26]
Hello there, 

I've been trying to use the moleculer-cli with a custom template to act as a service generator and upgrader. One of the last pieces to the puzzle is the new [promptForProjectOverwrite property](https://github.com/moleculerjs/moleculer-cli/issues/21). 

I noticed this morning when updating my moleculer-cli version that the new version hasn't been published to npm yet so the change can't be pulled down using npm install.

Can this be updated please? 

Thanks!

Amber

**Comment by icebob** [comment]
Published
