### ISSUE TITLE
npm run dev using AMQP and redis

### ISSUE THREAD

**Issue by dimkk** [moleculerjs/moleculer-cli#30]
Hey guys, first of all - thanks for your work! I will consider creating PR for this issue, but.

When I use cli, and select AMQP and Redis for caching I run 'npm run dev' which fails, because Redis and Rabbitmq is not running or configured, so my proposition will be - add steps to run/configure it.

Feedback appreceated. Thanks in advance.

**Comment by icebob** [comment]
The problem is that you install moleculer-cli as global so you need to install required libs as global for Redis & AMQP.
