### ISSUE TITLE
moleculer connect - transport issue using config

### ISSUE THREAD

**Issue by ipetrovic11** [moleculerjs/moleculer-cli#52]
Using `moleculer connect --config ./moleculer.config.js` transport is not loaded properly.

To verify this after running the command and executing `info` most of the config is loaded, while the transporter stays TCP

**Comment by icebob** [comment]
are you sure the path of config file is correct? Could you try to change e.g. namespace in config file and check with info?

**Comment by ipetrovic11** [comment]
Yes
![Screen Shot 2021-11-30 at 10 02 56 PM](https://user-images.githubusercontent.com/3995534/144127782-262094d3-7ad0-4602-bd9f-2879a8b41486.png)

And here is the config:
![Screen Shot 2021-11-30 at 10 03 16 PM](https://user-images.githubusercontent.com/3995534/144127814-77739b52-023d-40dc-95b3-f5ea4a63b73a.png)

**Comment by icebob** [comment]
And there is no defined `TRANSPORTER` env var? Because env var is stronger than config file.

**Comment by ipetrovic11** [comment]
100%

**Comment by icebob** [comment]
Then it's strange, because there is no default transporter, so if it's not defined, transporter won't be created. But in your case, somehow TCP transporter is defined.

**Comment by ipetrovic11** [comment]
I am not sure, but using this `moleculer connect redis://localhost-staging:30014 --ns=staging` works fine.

**Comment by icebob** [comment]
You are right, there is a strange if statement in the code:
https://github.com/moleculerjs/moleculer-cli/blob/f246a708b1419c19226a53ca3682bda136286123/src/connect-handler.js#L49-L56
