### ISSUE TITLE
deprecated coffee-script

### ISSUE THREAD

**Issue by veryphatic** [moleculerjs/moleculer-cli#8]
**What is the current behavior?**

Installing the cli tool throws the error: 

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

**What is the expected behavior?**

The installation should work as long as the dependencies point to the correct location

**Which versions of molecular-cli, and which browser / OS are affected by this issue? Did this work in previous versions?**

Building the library inside a Docker node:8 container with a non-root user -u 1000 on OS X

**Comment by icebob** [comment]
Moleculer-cli has no direct dependency on `coffee-script`, so I can't fix it. It comes from a sub-dependency.
